import Head from 'next/head'
import { Col, Container, Row } from 'react-bootstrap'

import { Overview, Pools } from '../components/Staking'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Row className="justify-content-center">
          <Col sm="12" md="10" lg="8" xl="7" className="d-flex flex-wrap">
            <Overview />
            <Pools />
          </Col>
        </Row>
      </Container>
    </div>
  )
}
